name:                hanoi
version:             0.1.0.0
github:              hjkcai/PLP4e
license:             MIT
author:              hjkcai
maintainer:          huajingkun1214@gmail.com
copyright:           2019 Jingkun Hua

dependencies:
- base >= 4.7 && < 5

executables:
  hanoi:
    main:                Main.hs
    source-dirs:         src
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
